template_admin
AT-PHPIntership/hotel-booking pull request #155
Opened 2017-08-02 10:08 UTC by at-annguyen

bower.json
.bowerrc
view/backend

2017-08-02 10:47 UTC, at-vienle commented
đặt tên file view không đúng rồi nhé. Ví dụ module category thì trong đó sẽ có các file như sau: 

- category
 - index.blade.php
 - show.blade.php
 - create.blade.php
 - edit.blade.php

2017-08-02 10:54 UTC, ghost requested changes
- tai sao 404 lại nằm trong thư mục này `resources/views/backend/login/404.html`
-  `resources/views/backend/login/login.html` 
- file login đặt ở đây ko đúng, sửa thành  `resources/views/backend/auth/login.blade.php`
- Đã đưa html vào resource thì phải sửa thành file `.blade` sao lại vẫn để `.html`

2017-08-02 10:54 UTC, at-vienle commented on resources/views/backend/layouts/main.blade.php
> +<script >
remove this script

2017-08-03 03:16 UTC, at-namnguyen commented
A Viện Rv lại giúp em

2017-08-03 03:42 UTC, ghost reviewed
@at-namnguyen
Check thư mục chưa object nhá! Nó là số nhiều.
Cấu trúc thư mục file views nó như thế này nha mọi người (từ thư mục `views`):
- backend
  - layouts
    - partials
      - `footer.blade.php`
      - `header.blade.php`
      - `leftbar.blade.php`
      - `scripts.blade.php`
      - `styles.blade.php`
    - `main.blade.php`
  - home
    - `index.blade.php`
  - hotels
    - ` index.blade.php`
    - `create.blade.php`
    - `show.blade.php`
    - `edit.blade.php`
  - bookings
    - ...
  - static_pages
    - ...
  - feedbacks
    - ...
  - news
    - ...
  - users
    - ...

2017-08-03 03:42 UTC, at-nhuibo commented on resources/views/backend/auth/login.blade.html
> +<!DOCTYPE html>
Cái ni sao lại là blade.html => .php chứ nhỉ?

Mấy cái file style, js, image? dùng `asset()` hết nha.

2017-08-03 04:06 UTC, at-namnguyen commented
anh Nhứi check giúp em
phần cấu trúc folder,
còn phần asset trong main và partials thì e đã update còn những trang chi tiết thì khi coding update luôn

2017-08-03 04:18 UTC, ghost approved these changes
LGTM. Thanks.

2017-08-03 04:20 UTC, merged