View List Of conment & rating
AT-PHPIntership/hotel-booking pull request #162
Opened 2017-08-04 03:19 UTC by at-namnguyen

2017-08-07 10:41 UTC, at-thinhnguyen commented on app/Http/Controllers/Admin/RatingCommentController.php
> +        $ratingComments = RatingComment::with(['users', 'hotels'])
ko nên select tất cả nhá

2017-08-07 10:43 UTC, at-thinhnguyen commented on app/Model/RatingComment.php
> +        return $this->belongsTo('App\Model\User', 'id');
chổ này cũng ko select all

2017-08-07 16:15 UTC, at-namnguyen commented
em mới update a check lại giúp em

2017-08-09 08:27 UTC, at-thinhnguyen commented on app/Http/Controllers/Admin/RatingCommentController.php
> +        // dd($ratingComments);
remove comment này đi

2017-08-09 09:06 UTC, at-namnguyen commented
Em mới Fix và update phần Translation a @at-thinhnguyen  rieview lại giúp e

2017-08-09 09:56 UTC, ghost requested changes
check my cmt

2017-08-09 09:56 UTC, at-vienle commented on app/Http/Controllers/Admin/RatingCommentController.php
> +                $query->addSelect('id', 'username', 'full_name');
dùng `addSelect` thì chạy vẫn chạy đúng, ko lỗi gì cả, nhưng sử dụng không đúng mục đích của hàm. `addSelect` là để add thêm columns vào 1 list các column đã có trước đó. 
Nên trường hợp này dùng `select` thì  sẽ đúng hơn

2017-08-09 09:56 UTC, at-vienle commented on resources/views/backend/comments/index.blade.php
> +                @foreach($ratingComments as $objRatingComment)
`$objRatingComment` tên biến thế này chưa thực sự hay, vì bản thân nó đã là object nên không nhất thiết phải thêm tiền tố `obj`. 
Những trường hợp loop thế này thì chỉ cần dùng số ít và số nhiều là ok. Số nhiều là thể hiện 1 list các item, còn số ít là 1 item.

2017-08-09 09:56 UTC, at-vienle commented on resources/views/backend/comments/index.blade.php
> +                        <input type="hidden" name="user_id" value="{{ $objRatingComment->id }}">
vì sao phải cần truyền đi cái id này?

2017-08-09 09:56 UTC, at-vienle commented on resources/views/backend/comments/index.blade.php
> +                        <input type="hidden" name="_method" value="DELETE">
thế này cũng OK, nhưng Laravel hỗ trơ `method_field()` helper đơn giản hơn. 
https://laravel.com/docs/5.4/helpers#method-method-field

2017-08-09 10:43 UTC, at-namnguyen commented on app/Http/Controllers/Admin/RatingCommentController.php
> +                $query->addSelect('id', 'username', 'full_name');
sorry a, vì chỗ này lúc e test còn để quên k xóa đi, e sẽ để tâm hơn :)

2017-08-09 10:43 UTC, at-namnguyen commented
em mới update a review lại giúp em

2017-08-09 10:44 UTC, at-namnguyen commented on resources/views/backend/comments/index.blade.php
> +                        <input type="hidden" name="user_id" value="{{ $objRatingComment->id }}">
sorry a, vì chỗ này lúc e test còn để quên k xóa đi, e sẽ để tâm hơn :)

2017-08-09 10:52 UTC, ghost requested changes
pls check my cmt

2017-08-09 10:52 UTC, at-vienle commented on app/Model/RatingComment.php
> +    public function users()
`RatingComment` belongs to `User` nên tại sao lại dùng số nhiều trong trường hợp này?

2017-08-09 10:52 UTC, at-vienle commented on app/Model/RatingComment.php
> +    public function hotels()
belongsTo sao lại số nhiều

2017-08-09 10:52 UTC, at-vienle commented on app/Http/Controllers/Admin/RatingCommentController.php
> +                $query->Select('id', 'username', 'full_name');
dùng `Select` hay `select` đều chạy, nhưng phải thống nhất, không nên có chỗ dùng `select` trong khi chỗ khác lại dùng `Select`. 
Recommend: Tên hàm thì nên dùng camel case, viết thường chữ đầu tiên

2017-08-09 10:52 UTC, at-vienle commented on resources/views/backend/comments/index.blade.php
> +                        <button class="glyphicon glyphicon-trash" onclick="
chỗ này bữa thống nhất là dùng jQuery để xử lý rồi mà. Hỏi @at-vudang vu
nhé @at-namnguyen nam

2017-08-09 11:05 UTC, at-namnguyen commented
em mới update a review lại giúp em @at-vienle

2017-08-09 11:05 UTC, at-namnguyen commented on resources/views/backend/comments/index.blade.php
> +                        <button class="glyphicon glyphicon-trash" onclick="
ok a, vậy sẽ dùng jquery

2017-08-10 04:35 UTC, ghost approved these changes
LGTM

2017-08-10 04:36 UTC, merged