Admin List News Story
AT-PHPIntership/hotel-booking pull request #163
Opened 2017-08-04 03:47 UTC by AT-DuocNguyen

2017-08-07 10:47 UTC, at-thinhnguyen commented on app/Http/Controllers/Admin/ListNewsController.php
> +        $news = News::with('category')->paginate(10);
ko nên select all

2017-08-07 10:47 UTC, at-thinhnguyen commented on app/Model/News.php
> +        'id','title', 'content','slug', 'category_id'
ko cần fillable slug

2017-08-10 01:26 UTC, ghost requested changes
@AT-DuocNguyen Please check my comments. Thanks.

2017-08-10 01:26 UTC, at-nhuibo commented on app/Http/Controllers/Admin/ListNewsController.php
> +        $news = News::select('id', 'title', 'slug', 'content', 'category_id')
Cái columns á! bỏ vào 1 cái biến cho nó dễ nhìn, review!
```php
$columns = [
  'id',
  'title',
  'slug',
  'content',
  'category_id'
];
... News::select($columns)->...

2017-08-10 01:26 UTC, at-nhuibo commented on app/Http/Controllers/Admin/ListNewsController.php
> +                    ->orderby('id', 'ASC')->paginate(10);
Ko hard code nha! Define 1 cái biến `ROW_LIMIT=10` ở model news rồi gọi dùng.
```php
...->paginate(News::ROW_LIMIT);
```

2017-08-10 01:26 UTC, at-nhuibo commented on app/Http/Controllers/Admin/ListNewsController.php
> +    public function create()
Mấy cái method này không dùng store, edit,... remove hết đi, để lại cái index thôi.

2017-08-10 01:26 UTC, at-nhuibo commented on app/Model/Image.php
> +    protected $table = 'images';
Thêm cái description cho nó nha!

2017-08-10 01:26 UTC, at-nhuibo commented on app/Model/Image.php
> +    protected $fillable = [
Description cho cái ni nữa!

2017-08-10 01:26 UTC, at-nhuibo commented on app/Model/Image.php
> +    public $timestamps = false;
Description cho cái ni nữa!

2017-08-10 01:26 UTC, at-nhuibo commented on app/Model/News.php
> +    protected $table = 'news';
Mấy cái biến $table, $fillable, $timestamp á, thêm description cho nó.
Và đặt nó lên trước.
Mấy các method thì để dưới.

2017-08-10 01:49 UTC, AT-DuocNguyen commented on app/Http/Controllers/Admin/ListNewsController.php
> +    public function create()
Mấy cái method đó  để dùng cho create, update, delete khi checkout ra nhánh mới á A Nhứi nên tạo để sẵn đó luôn

2017-08-10 01:57 UTC, at-nhuibo commented on app/Http/Controllers/Admin/ListNewsController.php
> +    public function create()
@AT-DuocNguyen 
Mình biết. Chỉ nên tạo khi nào làm thôi!
Chứ không để trơ trơ như thế.

2017-08-10 02:50 UTC, ghost reviewed
@AT-DuocNguyen có comment thêm á! Check dùm vs! ;)

2017-08-10 02:50 UTC, at-nhuibo commented on app/Http/Controllers/Admin/ListNewsController.php
> +                    'id',
Chỗ này dùng 1 tab thôi.
1tab trong php là 4 dấu cách mới chuẩn. sửa lại editor sao cho dấu tab = 4 space nhá!

2017-08-10 02:50 UTC, at-nhuibo commented on resources/lang/vi.json
> +
Sao lại có thêm file này? Bị dư dấu cách rồi..

2017-08-10 03:02 UTC, ghost reviewed
Sorry, mới phát hiện thêm 1 cái nữa!

2017-08-10 03:02 UTC, at-nhuibo commented on app/Http/Controllers/Admin/ListNewsController.php
> +class ListNewsController extends Controller
Tên file và class nên là NewsController thôi! Check lại chỗ này rồi file route nữa nhá!

2017-08-10 09:07 UTC, ghost requested changes
pls check my cmt

2017-08-10 09:07 UTC, at-vienle commented on resources/views/backend/news/index.blade.php
> +            <a href="/admin/news/create" class="btn btn-primary">
should use `route` function, dont use absolute path

2017-08-10 09:07 UTC, at-vienle commented on routes/web.php
> +	Route::group(['prefix' => 'news'], function () {
just use `resource`, don't use route group and prefix in this case

2017-08-10 09:20 UTC, at-vienle commented
@AT-DuocNguyen please resolve conflict

2017-08-10 09:32 UTC, ghost requested changes
pls check cmt

2017-08-10 09:32 UTC, at-vienle commented on resources/views/backend/news/index.blade.php
> +          <div class="btn-AddNews">
tên class và id viết thường và dùng dấu `-` để separate. `btn-AddNews` tên này ko đúng.
@AT-DuocNguyen Em fix giúp anh hết các lỗi thế này trong PR

2017-08-10 21:20 UTC, at-vienle commented
@AT-DuocNguyen please resolve conflict

2017-08-11 02:19 UTC, ghost approved these changes
LGTM

2017-08-11 02:19 UTC, merged