Admin edit news story
AT-PHPIntership/hotel-booking pull request #171
Opened 2017-08-04 08:23 UTC by AT-DuocNguyen

2017-08-11 01:19 UTC, ghost reviewed
Plz check my comments.

2017-08-11 01:19 UTC, at-nhuibo commented on app/Http/Controllers/Admin/NewsController.php
> +        $news->Update($request->all());
```php
$updateResult = $news->update($request->all());
if ($updateReult) {
...
```

2017-08-11 01:19 UTC, at-nhuibo commented on app/Http/Controllers/Admin/NewsController.php
> +            Session::flash(__('Edit News Fail!'))->error();
Use only `flash(...)` please, it is shorter.

2017-08-11 01:30 UTC, AT-DuocNguyen commented on app/Http/Controllers/Admin/NewsController.php
> +            Session::flash(__('Edit News Fail!'))->error();
OK I fixed it.

2017-08-11 01:48 UTC, ghost approved these changes
LGTM. Thanks.

2017-08-11 02:17 UTC, ghost requested changes
@AT-DuocNguyen 
Check comment của anh và chia nhỏ cái PR này ra, cái title là Edit news mà commit cả những file thuộc chức năng khác.

2017-08-11 02:17 UTC, at-vienle commented on app/Http/Controllers/Admin/NewsController.php
> +        $newsUpdate = News::findOrFail($id)->Update($request->all());
dùng `update` hay `Update` đều được, nhưng phải thống nhất, không được lúc cái này, lúc cái kia. 
Tên hàm thì thường dùng kiểu camel chữ đầu viết thường

2017-08-11 02:17 UTC, at-vienle commented on resources/views/backend/news/create.blade.php
> +    <h1 class="title_page">{{trans('admin_list_news.add_news')}}</h1>
Bữa trước thống nhất dùng translate kiểu string key rồi mà. 
https://laravel.com/docs/5.4/localization#using-translation-strings-as-keys

2017-08-11 04:05 UTC, ghost requested changes
pls check cmt

2017-08-11 04:05 UTC, at-vienle commented on app/Http/Controllers/Admin/NewsController.php
> +                    ->get();
Edit only 1 news so why you use `get` function, that function return an collection. Use `firstOrFail` instead

2017-08-15 03:04 UTC, ghost reviewed
Like with 
https://github.com/AT-PHPIntership/hotel-booking/pull/166#pullrequestreview-56252807
Pls check it again.
Thanks

2017-08-17 01:41 UTC, at-huydq2 commented on public/css/main.css
> +<<<<<<< HEAD
remove conflict !

2017-08-17 01:45 UTC, at-minhnguyen commented on app/Http/Controllers/Admin/NewsController.php
> +     /**
Please format style comment

2017-08-17 01:45 UTC, at-minhnguyen commented on app/Http/Controllers/Admin/NewsController.php
> +                    ->first();
You should use firstOrFail().
Auto redirect to page not found If news is not found

2017-08-17 01:45 UTC, at-minhnguyen commented on public/css/main.css
> +<<<<<<< HEAD
Please fix conflict code

2017-08-17 01:45 UTC, at-minhnguyen commented on resources/views/backend/news/edit.blade.php
> +      @include('flash::message')
Em check lại xem chỗ đặt message error, ở các page khác a thấy đặt trên.

2017-08-17 02:23 UTC, at-huydq2 commented on app/Http/Controllers/Admin/NewsController.php
> +                    ->first();
@at-minhnguyen i think if use `Slug`for find this ok and @AT-DuocNguyen need check :  

```
if (is_null($news)) { 
  throw new ModelNotFoundException; 
}
```
**(use \Illuminate\Database\Eloquent\ModelNotFoundException;)**

2017-08-17 06:53 UTC, merged