Admin delete place
AT-PHPIntership/hotel-booking pull request #177
Opened 2017-08-06 20:15 UTC by at-trungtranqn

- Admin delete place from list place

2017-08-07 04:01 UTC, at-thinhnguyen commented
sao có list trong này, tách ra 1 branch làm list trước
không select * nhá

2017-08-07 13:56 UTC, at-trungtranqn commented
Đã fix xong nha anh :)

2017-08-08 08:19 UTC, at-thinhnguyen commented on app/Http/Controllers/Admin/PlaceController.php
> +        $place = Place::findOrFail($id);
viết Exception chung cho trường hợp này, sáu đó check xoá thành công hoăc ko

2017-08-08 08:20 UTC, at-thinhnguyen commented on public/js/main.js
>  $(function () {
ko dùng DataTable thì nên xoá cái này đi

2017-08-08 08:21 UTC, at-thinhnguyen commented on routes/web.php
> +    Route::resource('/place', 'PlaceController');
"place" thôi đủ rùi :D, ko cần "/place"

2017-08-09 09:46 UTC, at-trungtranqn commented on app/Http/Controllers/Admin/PlaceController.php
> +        $place = Place::findOrFail($id);
ok a, đã có handle exception rồi nha

2017-08-10 07:19 UTC, ghost requested changes
check my cmt

2017-08-10 07:19 UTC, at-vienle commented on resources/views/backend/places/index.blade.php
> +                          <input type="hidden" name="id" value="{{ $place->id }}">
why do you need to add place id in this form?

2017-08-10 09:11 UTC, at-vienle commented
@at-trungtranqn please fix conflict

2017-08-10 21:18 UTC, ghost approved these changes
LGTM

2017-08-10 21:18 UTC, merged