Admin Categories List
AT-PHPIntership/hotel-booking pull request #179
Opened 2017-08-07 07:00 UTC by at-annguyen

2017-08-08 03:11 UTC, at-thinhnguyen commented
Fix conflict và xoá máy file không cần nữa: app/Admin/CatController.php, app/CatController.php, còn máy file blade sao tự nhiên xoá vậy?

2017-08-08 08:48 UTC, at-thinhnguyen commented
set lại permisstion máy file kia nữa

2017-08-09 08:40 UTC, at-thinhnguyen commented on app/Http/Controllers/Admin/CatController.php
> +<?php
đặt lại tên file là CategoryController luôn đê

2017-08-10 01:59 UTC, at-thinhnguyen commented on config/app.php
>      |
file này để như củ đi

2017-08-10 02:00 UTC, at-thinhnguyen commented on resources/lang/en/admin_categories.php
> +<?php
bỏ kiểu ni rồi mà

2017-08-10 02:00 UTC, at-thinhnguyen commented on resources/lang/en/admin_left-bar.php
> +<?php
xoá file này luôn

2017-08-10 02:03 UTC, at-thinhnguyen commented on resources/views/backend/layouts/main.blade.php
> +  <link rel="shortcut icon" href="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQnqy85GM3ND6RbF0m2V2x4kFCdOR8jub9YSWKk5y69kcSYzDkV" id="favicon">
file hình này đưa vào làm gì thế?

2017-08-10 02:04 UTC, at-thinhnguyen commented on resources/views/backend/layouts/partials/header.blade.php
> +              <img src="{{ asset('bower_components/AdminLTE/dist/img/user3-128x128.jpg') }}" class="user-image" alt="User Image">
hình gì ri ku :D

2017-08-10 02:05 UTC, at-thinhnguyen commented on resources/views/backend/layouts/partials/left-bar.blade.php
> +            <i class="fa fa-dashboard"></i> <span>{{ trans('admin_left-bar.home_page') }}</span>
Sửa lại ngôn ngữ, đổi sang kiểu key-string rùi

2017-08-10 02:07 UTC, at-thinhnguyen commented on tests/Browser/ListCategories.php
> +<?php
viết test qua nhánh khác

2017-08-10 02:29 UTC, at-annguyen commented on resources/views/backend/layouts/main.blade.php
> +  <link rel="shortcut icon" href="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQnqy85GM3ND6RbF0m2V2x4kFCdOR8jub9YSWKk5y69kcSYzDkV" id="favicon">
cái ảnh trên tab thôi anh

2017-08-10 04:53 UTC, at-thinhnguyen commented
fix conlict

2017-08-10 04:56 UTC, at-thinhnguyen commented on config/app.php
>      ],
file này ko chỉnh sửa, ko nên xoá dòng đó :3

2017-08-10 04:56 UTC, at-thinhnguyen commented on resources/views/backend/categories/create.blade.php
> +@section('title','Create Category Page')
đa ngôn ngữ chổ này nữa

2017-08-10 04:57 UTC, at-thinhnguyen commented on resources/views/backend/layouts/main.blade.php
> +  <link rel="shortcut icon" href="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQnqy85GM3ND6RbF0m2V2x4kFCdOR8jub9YSWKk5y69kcSYzDkV" id="favicon">
rứa thì tải về bỏ trong source luôn đi

2017-08-10 04:58 UTC, at-thinhnguyen commented
checkout lại file composer.lock

2017-08-10 07:20 UTC, at-thinhnguyen commented on app/Model/Category.php
> +    * Return value of parameter
"Return value of parameter" nó ko đúng, nên comment:
    /**
     * The table associated with the model.
     *
     * @var string
     */

2017-08-10 09:10 UTC, at-vienle commented
@at-annguyen please fix conflict. Thanks

2017-08-10 11:03 UTC, ghost requested changes
This PR is quite big. 
And pls check my cmt

2017-08-10 11:03 UTC, at-vienle commented on resources/views/backend/categories/create.blade.php
> +                  <input type="text" class="form-control has-error" id="InputName" placeholder="Input Category Name" value="" title="Input Name" name="name">
why class `has-error` always appear?

2017-08-10 11:03 UTC, at-vienle commented on resources/views/backend/categories/create.blade.php
> +                  <input type="text" class="form-control has-error" id="InputName" placeholder="Input Category Name" value="" title="Input Name" name="name">
`InputName` please change to `input-name`, id class should use dash case

2017-08-10 11:03 UTC, at-vienle commented on resources/views/backend/categories/create.blade.php
> +                  <input type="text" class="form-control has-error" id="InputName" placeholder="Input Category Name" value="" title="Input Name" name="name">
please translate `Input Category Name`

2017-08-10 11:03 UTC, at-vienle commented on routes/web.php
> +	Route::resource('/comment', 'RatingCommentController');
check the indent

2017-08-11 02:00 UTC, ghost approved these changes
LGMT

2017-08-11 02:00 UTC, merged