Admin update place
AT-PHPIntership/hotel-booking pull request #205
Opened 2017-08-13 06:39 UTC by at-trungtranqn

Admin update place

2017-08-14 04:11 UTC, ghost requested changes
Có image preview luôn. (y)
Check lại 1 số chỗ mình comment vs!

2017-08-14 04:11 UTC, at-nhuibo commented on app/Http/Controllers/Admin/PlaceController.php
> +            $fileName = config('constant.current_day')."-".$file->getClientOriginalName();
- Trước và sau dấu nối có 1 dấu cách nha
- Tên file khi lưu vào thì phải chuyển thành string random và unique, có thể prefix ngày/hoặc phân thư mục theo ngày, ko đc để tên gốc của file.

2017-08-14 04:11 UTC, at-nhuibo commented on app/Http/Controllers/Admin/PlaceController.php
> +        $arrayPlace = $request->all();
`$arrayPlace` đổi thành `$input` đi. Vì cái này là do user nhập vào mà. Chứ để `$arrayPlace` thì chung chung quá...

2017-08-14 04:11 UTC, at-nhuibo commented on app/Http/Controllers/Admin/PlaceController.php
> +            $arrayPlace['image'] = $fileName;
Nên viết 1 hàm chung chuyên về upload ảnh. Ví dụ như sau:
```php
$input['image'] = $this->uploadSingleImage($fieldName = 'image', $path = config('constant.path_upload_places'));
```

2017-08-14 09:13 UTC, at-trungtranqn commented on app/Http/Controllers/Admin/PlaceController.php
> +            $arrayPlace['image'] = $fileName;
Up một ảnh nên chỉ dùng cho place thôi nha A Nhứi, nên mình sẽ không tách thành function

2017-08-14 09:47 UTC, ghost reviewed
LGTM. Thanks.

2017-08-14 09:47 UTC, ghost approved these changes

2017-08-17 02:58 UTC, ghost reviewed
Trung check lại vs! ;)

2017-08-17 02:58 UTC, at-nhuibo commented on config/constant.php
>  return [
Đổi tên file này thành define.php đi!

2017-08-17 02:58 UTC, at-nhuibo commented on app/Http/Controllers/Admin/PlaceController.php
> +        $place = Place::find($id);
FindOrFail() luôn nha!

2017-08-17 03:08 UTC, at-nhuibo commented on app/Http/Requests/Backend/UpdatePlaceRequest.php
> +            'descript' => 'required'
Thêm cái image nữa nha! `nullable|image|size_define_max_size`

2017-08-17 07:05 UTC, ghost reviewed
Please check my comments. Cám ơn ;) Ahihi...

2017-08-17 07:05 UTC, ghost commented on app/Http/Requests/Backend/CreatePlaceRequest.php
> +            'image' => 'required|image|max:10000',
10MB = ?KB. please define 10MB in config.define file.
Check xem chỗ khác cũng vại nha bấy bì!

2017-08-17 07:05 UTC, at-nhuibo commented on app/Model/Place.php
> +        return config("define.path_upload_places").$this->image;
Cái này ghi đè cái có sẵn luôn... Dùng `setImageAttribute()` á.
Nhớ thêm dấu cách trước vài sau dấu nối: `.`.

2017-08-17 07:05 UTC, at-nhuibo commented on resources/views/backend/places/edit.blade.php
> +                  <label for="descript">{{ __('Descript') }}</label>
Cái ni nên ghi đầy đủ là `Description` luôn nha!

2017-08-17 07:05 UTC, at-nhuibo commented on resources/views/backend/places/edit.blade.php
> +                  href="{{route('place.index')}}">
Chỗ ni dùng ri hay hơn: `href="javascript:history.back()"`.
Làm rày thì nếu như họ đang ở trang 10 chẳng hạn, họ bấm edit, rồi họ bấm back, hắn sẽ về đúng y trang 10.

2017-08-17 09:08 UTC, at-trungtranqn commented
Thanks for your comment :)

2017-08-17 09:11 UTC, ghost reviewed
Cái `name_prefix` ni là dùng chung nha! Ko chỉ places dùng nên bỏ ở ngoài nhá!

2017-08-17 09:11 UTC, at-nhuibo commented on app/Http/Controllers/Admin/PlaceController.php
> +            $fileName = config('image.places.name_prefix') . "-" . $file->hashName();
Cái `name_prefix` ni là dùng chung nha! Ko chỉ places dùng nên bỏ ở ngoài nhá!

2017-08-17 09:12 UTC, at-huydq2 commented on app/Model/Place.php
> +        return asset(config("image.places.path_upload") . $this->image);
please check image if not exist in `folder Path` . if not exist :  return url image default;

2017-08-17 09:14 UTC, at-nhuibo commented on app/Model/Place.php
> +        return asset(config("image.places.path_upload") . $this->image);
e nghĩ hk cần đâu a! Vì cái ni chắc chắn có rồi ạ!

2017-08-17 09:14 UTC, at-nhuibo commented on app/Model/Place.php
> +        return asset(config("image.places.path_upload") . $this->image);
@at-huydq2 ...

2017-08-17 09:53 UTC, at-nhuibo commented on app/Http/Controllers/Admin/PlaceController.php
> +            $fileName = config('image.places.name_prefix') . "-" . $file->hashName();
@at-trungtranqn fix cái này đê... để a min mợch

2017-08-17 10:21 UTC, ghost approved these changes
LGTM. Thanks.

2017-08-18 02:44 UTC, merged