admin show detail user
AT-PHPIntership/hotel-booking pull request #221
Opened 2017-08-17 05:48 UTC by at-yenho

2017-08-17 07:13 UTC, ghost requested changes
Please check my comments. Thanks

2017-08-17 07:13 UTC, at-nhuibo commented on public/css/main.css
> +.mr-0 {
Cái này gọi là .mlr-0 thì đúng hơn.

2017-08-17 07:13 UTC, at-nhuibo commented on public/css/main.css
> +.mr-l-5per {
`.ml-5per` viết tắt của margin-left.
ở đây á. Mấy cái margin-left, hay right hay top hay bottom, mình nên để nó ở 1 chỗ. để dùng chung. rồi ai dùng chỗ nào đó thì dùng.

2017-08-17 07:13 UTC, at-nhuibo commented on resources/views/backend/users/index.blade.php
> +                      <td>{{ $user->password }}</td>
Không cần show password trong list nha!

2017-08-17 07:13 UTC, at-nhuibo commented on resources/views/backend/users/show.blade.php
> +        <img src="{{ asset('images/users/hinh-nen-dep-10_044004.jpg') }}"
Cái ni là sao? hinh-nen-dep???

2017-08-17 07:13 UTC, at-nhuibo commented on resources/views/backend/users/show.blade.php
> +              Admin
Cái ni dùng language luôn nha!

2017-08-17 07:13 UTC, at-nhuibo commented on resources/views/backend/users/show.blade.php
> +              User
Dùng lang

2017-08-17 07:13 UTC, at-nhuibo commented on resources/views/backend/users/show.blade.php
> +              Actived
Đây nữa...

2017-08-17 07:13 UTC, at-nhuibo commented on resources/views/backend/users/show.blade.php
> +              Disabled
Này nữa... Ahii...

2017-08-17 14:45 UTC, ghost approved these changes
LGTM. Thanks.

2017-08-18 03:34 UTC, at-thinhnguyen commented on resources/views/backend/users/show.blade.php
> +        <img src="{{ asset('images/users/profile-user.png') }}" class="img-profile">
2 cái image ni là gì vậy e?

2017-08-18 03:39 UTC, at-thinhnguyen commented
e xem coi template profile khác thử :D

2017-08-18 03:58 UTC, at-nguyenvo commented
Anh nghĩ em nên dùng luôn form của adminlte để làm details luôn nhé em. Giống bên food đang làm. Dựng form kiểu như thế này và thay text field bằng label hoặc em có thể để readonly. 
Click vào button edit thì enable là được. 
Cái form hiện tại em đang làm nó ko theo 1 cái style nào hết.... nhìn không được chuyên nghiệp lắm. 

![screen shot 2017-08-18 at 10 56 35 am](https://user-images.githubusercontent.com/14899260/29443696-f82d86d8-8403-11e7-8aaf-5661001005cc.png)

2017-08-18 04:13 UTC, ghost reviewed
Trong file ```main.css``` có 2 css trùng nhau đó là ```margin-center```
Nếu em dùng 
```
.margin-center {
    margin-left: 15%;
    margin-right: 15%;
}
```
Em có thể viết lại bằng cách:
```
.margin-center {
    margin: 0 15%;
}
```
CSS này chắc đã đc học bên FE. :)

2017-08-18 04:13 UTC, at-nguyenvo commented on public/css/main.css
> +}
Bootstrap có 1 cái css:
```
  .col-xs-offset-0 {
    margin-left: 0;
  }
  .col-sm-offset-0 {
    margin-left: 0;
  }
  .col-md-offset-0 {
    margin-left: 0;
  }
  .col-lg-offset-0 {
    margin-left: 0;
  }

```
Em có thể dùng lại class này. Vì default trong bootstrap margin chỉ được set cho ``` margin-left``` thôi. Nên em không cần phải khai báo css thêm cho cái này.

2017-08-21 01:53 UTC, at-thinhnguyen commented on resources/views/backend/users/show.blade.php
> +                <div class="form-control text-center fz-16 mt-20 col-md-offset-2">{{ ($user->is_active == App\Model\User::STATUS_ACTIVED)? __('Actived'): __('Disabled') }}</div>
chổ này e nên viết 1 cái getAttribute

2017-08-21 02:00 UTC, at-thinhnguyen commented on resources/views/backend/users/show.blade.php
> +               src="{{ asset('images/users/profile.png') }}">
cái hình này ko có à em, chắc kiếm cái hình mặc định lun

2017-08-21 02:00 UTC, at-thinhnguyen commented on resources/views/backend/users/show.blade.php
> +               src="{{ asset('images/users/profile.png') }}">
em đưa cái hình mặc định đó lên

2017-08-21 02:02 UTC, at-yenho commented on resources/views/backend/users/show.blade.php
> +               src="{{ asset('images/users/profile.png') }}">
user k có avatar nên hình này là hình mặt định rồi a

2017-08-21 02:04 UTC, at-yenho commented on resources/views/backend/users/show.blade.php
> +                <div class="form-control text-center fz-16 mt-20 col-md-offset-2">{{ ($user->is_active == App\Model\User::STATUS_ACTIVED)? __('Actived'): __('Disabled') }}</div>
e viết 2 hàm getAttribute cho role vs status thôi phải k a?

2017-08-21 03:06 UTC, at-thinhnguyen commented
đợi circleci chạy xong rùi assign nhá gái

2017-08-21 04:02 UTC, at-thinhnguyen commented on resources/views/backend/users/show.blade.php
> +               src="{{ asset('images/users/profile.png') }}">
cái hình mặc định này chỉ máy em có thôi, chứ máy khác đâu có đâu

2017-08-21 04:03 UTC, at-yenho commented on resources/views/backend/users/show.blade.php
> +               src="{{ asset('images/users/profile.png') }}">
Dạ e push lên rồi á

2017-08-21 04:09 UTC, at-thinhnguyen commented on app/Model/User.php
> +        return $this->is_admin == $this->ROLE_ADMIN? __('Admin'): __('User');
self::ROLE_ADMIN

2017-08-21 04:25 UTC, at-thinhnguyen commented
LGTM

2017-08-21 09:11 UTC, at-minhnguyen commented
LGTM

2017-08-21 09:11 UTC, merged