Admin create room
AT-PHPIntership/hotel-booking pull request #251
Opened 2017-08-22 16:28 UTC by at-yenho

2017-08-23 07:31 UTC, at-thinhnguyen commented on app/Http/Controllers/Admin/RoomController.php
> +        /**
chỉnh lại convention  nhá gái

2017-08-23 07:33 UTC, at-thinhnguyen commented on app/Http/Controllers/Admin/RoomController.php
> +        Hotel::findOrFail($hotelId);
nếu muốn kiểm tra $hotelId tồn lại không, anh nghĩ e nên tạo 1 cái request rùi check exists in database

2017-08-23 07:33 UTC, at-thinhnguyen commented on app/Http/Controllers/Admin/RoomController.php
> +        Hotel::findOrFail($hotelId);
và xuống view e chỉ cần gọi request()->id được rồi, không cần truyền từ controller xuông đâu

2017-08-23 07:35 UTC, at-thinhnguyen commented on public/js/main.js
> +            console.log(imgpath);
remove

2017-08-24 01:34 UTC, at-thinhnguyen commented on app/Http/Controllers/Admin/RoomController.php
> +        $room = new room($request->all());
Room nhá

2017-08-25 05:11 UTC, ghost requested changes
Please check my comments. Thanks.

2017-08-25 05:11 UTC, at-nhuibo commented on app/Http/Requests/Backend/RoomRequest.php
> +            'image' => 'nullable|max:' . config('image.max_upload_size'),
Cái ni là required nhá.
```php
'images' => 'required|array',
'images.*' => 'image|max:' . config('image.max_upload_size')
```

2017-08-25 05:11 UTC, at-nhuibo commented on resources/views/backend/rooms/create.blade.php
> +                  <input type="file" class="form-control" name="image[]" id="multiple-image" multiple>
Multiple thì nên đặt tên input là số nhiều luôn nhá!

2017-08-25 05:11 UTC, at-nhuibo commented on app/Http/Controllers/Admin/RoomController.php
> +        if (isset($request->image)) {
Cái image là required, nên hk cần check nhá!!!!

2017-08-25 05:11 UTC, at-nhuibo commented on resources/views/backend/rooms/create.blade.php
> +              <h3 class="box-title lead">{{ __("Enter infomation") }}</h3>
Nên hiển thị thông tin hotel, ít nhất là tên nhá.

2017-08-25 07:48 UTC, at-yenho commented on resources/views/backend/rooms/create.blade.php
> +              <h3 class="box-title lead">{{ __("Enter infomation") }}</h3>
Hiển thị ở đây á a
@section('content')
  <div class="content-wrapper">
    <h1 class="text-center text-success">
      {{ $hotel->name.__(' HOTEL') }}
    </h1>
    <h1 class="text-center text-success">
      @include('flash::message')
      {{ __("Create room") }}
    </h1>
    <!-- Main content -->

2017-08-25 08:04 UTC, at-nhuibo commented on resources/views/backend/rooms/create.blade.php
> +              <h3 class="box-title lead">{{ __("Enter infomation") }}</h3>
@at-yenho OK, thấy rồi! (y)

2017-08-25 08:06 UTC, at-nhuibo commented on resources/views/backend/rooms/create.blade.php
> +                    <img class="img-place" id="default-image" src="{{ asset('/images/default/no_image.png') }}">
Cái ni bỏ vào config trong file image vs nha: `/images/default/no_image.png`

2017-08-25 09:55 UTC, ghost approved these changes
LGTM. Thanks.

2017-08-29 01:29 UTC, at-minhnguyen commented
LGTM

2017-08-29 01:29 UTC, merged