Admin update room of hotel
AT-PHPIntership/hotel-booking pull request #261
Opened 2017-08-23 13:11 UTC by at-yenho

2017-08-25 10:35 UTC, ghost reviewed
Xem comment của a vs!

2017-08-25 10:35 UTC, at-nhuibo commented on app/Http/Controllers/Admin/ImageController.php
> +     * @return int
Please return boolean here.

2017-08-25 10:35 UTC, at-nhuibo commented on app/Http/Controllers/Admin/ImageController.php
> +            return 1;
return true;

2017-08-25 10:35 UTC, at-nhuibo commented on app/Http/Controllers/Admin/ImageController.php
> +        return 0;
return false;

2017-08-25 10:35 UTC, at-nhuibo commented on resources/views/backend/rooms/edit.blade.php
> +                    <img class="img-place" id="default-image" src="{{ asset('/images/default/no_image.png') }}">
Dùng config('image.no_image')

2017-08-25 10:35 UTC, at-nhuibo commented on public/js/main.js
> +                type: "GET",
Dùng phương thức delete nhá!
Nếu get ri thì ng ta vô browser gõ đúng cái link là ảnh nó bị xoá rồi.

2017-08-25 10:35 UTC, at-nhuibo commented on public/js/main.js
> +            console.log(imgpath);
remove cái này vs!

2017-08-25 12:30 UTC, at-yenho commented on app/Http/Controllers/Admin/ImageController.php
> +     * @return int
return boolean ở đây ajax k lấy được á a, e thấy chỉ trả về html, json, xml hoặc text

2017-08-28 02:52 UTC, ghost requested changes
Check lại giúp vs nha!

2017-08-28 02:52 UTC, at-nhuibo commented on app/Http/Controllers/Admin/ImageController.php
> +    public function removeImage($id)
Dùng cái hàm default của Laravel đi e! destroy á!

2017-08-28 02:52 UTC, at-nhuibo commented on public/js/main.js
> +                url: '/admin/image/removeImage/' + id_image,
Cái ni: `'/admin/image/removeImage/' + id_image`, đừng để cứng ri nha, ri là hard code á.
E lấy ra như thế này nhá:
```javascript
var url = $(this).attr('data-url');
```
Trong cái `data-url` thì echo ra full url để xoá luôn.

2017-08-28 02:52 UTC, at-nhuibo commented on routes/web.php
> +    Route::delete('/image/removeImage/{id}', 'ImageController@removeImage');
Dùng resource luôn nha, rồi thêm cái only vào,để cho phép method destroy thôi.

2017-08-28 05:07 UTC, ghost requested changes
A còn cái nớ thôi e! :D

2017-08-28 05:07 UTC, at-nhuibo commented on resources/views/backend/rooms/edit.blade.php
> +                            value="{{$img->id}}"
remove cái này...

2017-08-28 05:07 UTC, at-nhuibo commented on resources/views/backend/rooms/edit.blade.php
> +                            data-title="{{ __('Confirm deletion!') }}"
Cái data-token, data-title và data-confirm á.
Bỏ lên `#old-images` đi, để tránh bị lặp trong foreach, giảm đc size của file view.

2017-08-28 07:09 UTC, ghost reviewed
Có comment thêm e nhé! ;)

2017-08-28 07:09 UTC, at-nhuibo commented on public/js/main.js
> +        var img_comtainer = $('#old-images');
container nhé, hk phải com. :D

2017-08-28 07:09 UTC, at-nhuibo commented on public/js/main.js
> +        var token = img_comtainer.data('token');
Sao lúc dùng data(), lúc dùng attr() vại?

2017-08-28 07:09 UTC, at-nhuibo commented on public/js/main.js
> +        var remove_id = $(this).parent().attr('id');
cái này nên là `var img_item = $(this).parent();` rồi ở dưới thì remove ri thôi: `img_item.remove()`

2017-08-28 07:48 UTC, ghost approved these changes
LGTM. Thanks.

2017-08-29 01:55 UTC, at-minhnguyen commented
LGTM

2017-08-29 01:55 UTC, merged