Admin create hotel
AT-PHPIntership/hotel-booking pull request #266
Opened 2017-08-24 04:02 UTC by at-namnguyen

2017-08-24 04:36 UTC, at-namnguyen commented
anh @at-minhnguyen  RV giup e

2017-08-25 08:02 UTC, ghost reviewed
Nam check comment vs nha! ;)

2017-08-25 08:02 UTC, at-nhuibo commented on app/Http/Controllers/Admin/HotelController.php
> +        $places = Place::select('id', 'name')->get();
Dùng biến `$cols = [id', 'name'];` rồi dùng truyền vào select, cho nó ko bị lặp.

2017-08-25 08:02 UTC, at-nhuibo commented on app/Http/Controllers/Admin/HotelController.php
> +        if ($request->hasFile('images')) {
Dùng cái ni với nha: 
`Image::storeImages($request->images, 'room', $room->id, config('image.rooms.path_upload'));`

2017-08-25 08:02 UTC, at-nhuibo commented on app/Http/Requests/Backend/HotelCreateRequest.php
> +            'images' => 'required|image'
Chỗ images thì nên thế này nhá:
```php
'images' => 'required|array',
'images.*' => 'image|max:' . config('image.max_upload_size')
```

2017-08-25 08:02 UTC, at-nhuibo commented on public/js/main.js
> +    $( "#img-upload" ).change(function() {
Dùng chung từ bên ni nhá: https://github.com/AT-PHPIntership/hotel-booking/pull/269/files

2017-08-28 02:56 UTC, ghost requested changes
@at-namnguyen check lại giúp vs nha!

2017-08-28 02:56 UTC, at-nhuibo commented on resources/views/backend/hotels/create.blade.php
> +                      @for($i = 1; $i <= 5; $i++ )
Cái 1 vs 5 ni define ở Model hotel đi nha! Rồi lấy ở đây.

2017-08-28 02:56 UTC, at-nhuibo commented on resources/views/backend/hotels/create.blade.php
> +                    <img class="img-place" id="default-image" src="{{ asset('/images/default/no_image.png') }}">
Cái default image ni lấy ra từ config nha! ;)

2017-08-28 04:38 UTC, at-namnguyen commented
@at-nhuibo check lại giúp em

2017-08-28 04:45 UTC, ghost approved these changes
LGTM. Thanks.

2017-08-28 05:01 UTC, at-huydq2 commented on app/Http/Controllers/Admin/HotelController.php
> +        $services = Service::select($columns)->get();
chỗ này có nên cho mấy bạn dùng ViewComposers ko @at-nhuibo .

2017-08-28 07:12 UTC, at-nhuibo commented on app/Http/Controllers/Admin/HotelController.php
> +        $services = Service::select($columns)->get();
@at-huydq2 Cái ni chỉ dùng chỗ ni thôi nên e nghĩ là hk cần ạ!

2017-08-28 07:13 UTC, at-huydq2 commented on app/Http/Controllers/Admin/HotelController.php
> +        $services = Service::select($columns)->get();
oke Nhứi.
LGTM.

2017-08-29 02:20 UTC, at-minhnguyen commented
LGTM

2017-08-29 02:20 UTC, merged