Admin show hotel detail
AT-PHPIntership/hotel-booking pull request #268
Opened 2017-08-24 09:03 UTC by at-namnguyen

2017-08-24 10:12 UTC, at-namnguyen commented
@at-minhnguyen Anh Rv giup em

2017-08-25 04:10 UTC, ghost requested changes
Check comment với nha!

2017-08-25 04:10 UTC, ghost commented on app/Http/Controllers/Admin/HotelController.php
> +            select('id', 'name', 'address', 'star', 'introduce', 'place_id')
Ri cho gọn nhá!
```php
$columns = ['id', 'name', 'address', 'star', 'introduce', 'place_id'];
$with['place'] = function ($query) {
    $query->select('id', 'name');
};
$with['rooms'] = function ($query) {
    $query->select('id', 'hotel_id', 'name');
};
$hotel = Hotel::select($columns)
                   ->with($with)
                   ->findOrFail($id)
```

2017-08-25 04:10 UTC, at-nhuibo commented on app/Http/Controllers/Admin/HotelController.php
> +        $hotelServices = HotelService::select('id', 'hotel_id', 'service_id')->where('hotel_id', $id)
Cái này dùng quan hệ đi, rồi dùng with để lấy ra.

2017-08-25 04:10 UTC, at-nhuibo commented on app/Http/Controllers/Admin/HotelController.php
> +        $hotelImages = Image::select('path')->where([
Cái này cũng có thể định nghĩa quan hệ và lấy ra chỉ vs with.

2017-08-25 04:10 UTC, at-nhuibo commented on app/Http/Controllers/Admin/HotelController.php
> +        $countImages = count($hotelImages);
dùng quan hệ rồi count, ko cần get.

2017-08-25 07:42 UTC, at-nhuibo commented on app/Http/Controllers/Admin/HotelController.php
> +        $totalImages = count($hotel->images);
Không cần tạo biến này rồi gởi ra view đâu.
Ở view muốn check thì chỉ cần ri: `$hotel->images->count()`, hotel service vs rooms cũng vậy

2017-08-25 07:46 UTC, at-nhuibo commented on resources/views/backend/hotels/show.blade.php
> +        <h3>{{ __('Service').' ('.$totalServices.')' }}</h3>
Trước và sau dấu nối chuỗi `.` có 1 dấu cách nha!

2017-08-25 07:46 UTC, at-nhuibo commented on resources/views/backend/hotels/show.blade.php
> +        <h3>{{ __('Rooms').' ('.$totalRooms.')' }}</h3>
Dấu cách trước và sau dấu nối chuỗi

2017-08-25 09:15 UTC, at-nhuibo commented on resources/views/backend/hotels/show.blade.php
> +                  <img src="{{ asset('/images/default/default-thumbnail.jpg') }}">
Could you please put this into `config/image.php`.
Name should be `default_thumbnail `.
Just use it like this here: `asset(config('image.default_thumbnail'))`.

2017-08-25 09:52 UTC, ghost approved these changes
LGTM. Thanks.

2017-08-25 10:50 UTC, at-minhnguyen commented
LGTM

2017-08-25 10:50 UTC, merged