Show hotel
AT-PHPIntership/hotel-booking pull request #337
Opened 2017-09-04 01:02 UTC by at-trungtranqn

2017-09-14 03:27 UTC, ghost reviewed
check comment @at-trungtran

2017-09-14 03:27 UTC, ghost commented on app/Http/Controllers/Frontend/HotelController.php
> +        $checkoutDateDefaut = Carbon::tomorrow('Asia/Bangkok')->addWeeks(Hotel::WEEK_NUMBER);
vì sao lại dùng timezone vầy ?
muốn dùng timezone này thì set trong app config nhé!

2017-09-14 03:27 UTC, ghost commented on app/Model/Hotel.php
> +        $rating = $this->ratingComments()->avg('total_rating');
dùng collection avg dc rồi , ko phải dùng query nhé `ratingComments()` => `ratingComments`

2017-09-14 03:27 UTC, ghost commented on app/Model/Hotel.php
> +        } elseif (self::LOW_SCORE < $rating && $rating <= self::NOMAL_SCORE) {
chỉ cần check vế sau thôi. ko cần check vế trước

2017-09-14 03:27 UTC, ghost commented on app/Model/Hotel.php
> +        } elseif (self::NOMAL_SCORE < $rating && $rating <= self::HIGH_SCORE) {
như trên, check vế sau là đủ rồi

2017-09-14 03:27 UTC, at-huydq2 commented on resources/views/frontend/hotels/show.blade.php
> +      <section class="standard-slider hotel-slider">
check có ảnh mới thêm section của slider vào nhé

2017-09-14 06:44 UTC, at-trungtran commented on resources/views/frontend/hotels/show.blade.php
> +      <section class="standard-slider hotel-slider">
mình check rồi nha

2017-09-14 08:44 UTC, ghost requested changes
Check comment của mền nha ;)

2017-09-14 08:44 UTC, at-nhuibo commented on app/Http/Controllers/Frontend/HotelController.php
> +        $with['hotelServices.service'] = function ($query) {
Cái ni xem lại quan hệ nha.
Hắn có `belongsToMany` j đó mà! Chứ hk có lấy cái `hotelServices `.
Viết 1 cái quan hệ tên là `services` ở hotel, rồi dùng kiểu quan hệ trên. ;)

2017-09-14 08:44 UTC, at-nhuibo commented on app/Http/Controllers/Frontend/HotelController.php
> +            ->leftJoin(DB::raw("(SELECT busy_reservations.room_id as room_id, SUM(busy_reservations.quantity) as quantity_busy_reservation FROM (SELECT * FROM reservations WHERE (checkin_date < ? AND
Thiếu 2 cái status nữa nha!

2017-09-14 08:44 UTC, at-nhuibo commented on app/Model/RatingComment.php
> +        return sprintf("%.1f", $this->total_rating);
"%.1f" define trong config nha! ;)

2017-09-14 08:44 UTC, at-nhuibo commented on routes/web.php
> +    Route::resource('/hotel', 'HotelController');
Đổi hotel => hotels, 2 cái route ni nha
Thêm only `index` nữa nha

2017-09-14 08:44 UTC, at-nhuibo commented on routes/web.php
>  Route::group(['namespace'=>'Frontend', 'as' => 'frontend.'], function() {
Dứoi ni bị lặp rồi tề

2017-09-15 10:35 UTC, at-nhuibo commented on app/Http/Controllers/Frontend/HotelController.php
> +            ->leftJoin(DB::raw("(SELECT busy_reservations.room_id as room_id, SUM(busy_reservations.quantity) as quantity_busy_reservation FROM (SELECT * FROM reservations WHERE (status = ?) AND(chec
Query dài quá, rút gọn ri và format lại cho đẹp:
```php
$joinQuery = <<<EOD
(
    SELECT busy_reservations.room_id as room_id, SUM(busy_reservations.quantity) as quantity_busy_reservation
    FROM (
        SELECT * FROM reservations 
        WHERE (status = ?) AND (checkin_date < ? AND checkout_date > ?) 
            OR (checkin_date < ? AND checkout_date > ?)
    ) AS busy_reservations 
    GROUP BY busy_reservations.room_id
) AS busy_rooms
EOD;
```

2017-09-18 06:57 UTC, at-nhuibo commented on resources/views/frontend/hotels/partials/room.blade.php
> +                {{ __('Only :number_room_empty room(s) left', ['number_room_empty' => ($room->total - $room->quantity_busy_reservation)] ) }}
Dùng biến ni luôn chứ: `$totalRoomEmpty`, mắc chi phải tính lại.

2017-09-18 09:16 UTC, ghost approved these changes
LGTM. Thanks.

2017-09-18 10:03 UTC, at-minhnguyen commented
LGTM

2017-09-18 10:03 UTC, merged