User list hotel - FE
AT-PHPIntership/hotel-booking pull request #347
Opened 2017-09-08 02:10 UTC by at-yenho

2017-09-08 09:32 UTC, ghost requested changes
Xem review nhá!

2017-09-08 09:32 UTC, at-nhuibo commented on app/Http/Controllers/Frontend/HotelController.php
> +        $topPlaces = Hotel::select(['place_id'])
Cái ni là lấy cái place mà có số người đặt nhiều nhất trong vòng 1 tháng.

2017-09-08 09:32 UTC, at-nhuibo commented on public/css/main.css
> +<<<<<<< HEAD
Remove cái ni nhá.

2017-09-08 09:32 UTC, at-nhuibo commented on resources/views/frontend/hotels/index.blade.php
> +            <input type="text" class="form-control" name="x" placeholder="Search term...">
Xem cái ni nha: https://github.com/AT-PHPIntership/hotel-booking/pull/348#discussion_r137742586

2017-09-08 09:32 UTC, at-nhuibo commented on resources/views/frontend/hotels/index.blade.php
> +                    <div class="price">® ® ® ® </div>
Cái ni là star đi nha!

2017-09-08 09:32 UTC, at-nhuibo commented on resources/views/frontend/hotels/index.blade.php
> +                          @if ($key == 0 || $key == 3)
Chỗ này hơi rắc rối tí, khó hiểu.
Mà nên bỏ máy cái số ni trong config nha.

2017-09-08 09:32 UTC, at-nhuibo commented on resources/views/frontend/hotels/index.blade.php
> +                    <a href="/detailHotel" class="btn btn-primary btn-block">Read More</a>
Dùng __()

2017-09-08 09:32 UTC, at-nhuibo commented on resources/views/frontend/hotels/show.blade.php
> +            <div class="item"> <a href="images/rooms/slider/750x481.gif" data-rel="prettyPhoto[gallery1]">
Image ni cũng phải có asset nha.

2017-09-08 09:32 UTC, at-nhuibo commented on resources/views/frontend/hotels/show.blade.php
> +          <h1>Hotel Name</h1>
Dùng trans và echo ra phù hợp thông tin hỷ!

2017-09-10 13:35 UTC, at-yenho commented on resources/views/frontend/hotels/show.blade.php
> +            <div class="item"> <a href="images/rooms/slider/750x481.gif" data-rel="prettyPhoto[gallery1]">
file ni em đổi tên thôi chứ chưa đụng chi tới show detail hotel á a

2017-09-12 02:55 UTC, ghost reviewed
Check lai giúp vs nha!

2017-09-12 02:55 UTC, ghost commented on app/Model/Reservation.php
> +     * Define a value maximum duratiom
duration, ends by `n`, not `m`

2017-09-12 02:55 UTC, ghost commented on resources/views/frontend/hotels/index.blade.php
> +            <form class="reservation-horizontal clearfix container-search" action="/search" name="reservationform" >
Cái route trong `action` này có chưa?

2017-09-12 02:55 UTC, ghost commented on resources/views/frontend/hotels/index.blade.php
> +                    <div class="popover-icon" data-container="body" data-toggle="popover" data-trigger="hover" data-placement="right" data-content="Vivamus sagittis lacus vel augue laoreet rutrum fau
`data-content` có dùng hk? nếu hk thì remove nhá!

2017-09-12 02:55 UTC, ghost commented on resources/views/frontend/hotels/index.blade.php
> +                    <input type="text" name="hotelSourceArea" id="hotelSourceArea" class="form-control" value="" placeholder="Place to go">
`Place to go` dùng `_()` nha!

2017-09-12 02:55 UTC, ghost commented on resources/views/frontend/hotels/index.blade.php
> +                    <div class="popover-icon" data-container="body" data-toggle="popover" data-trigger="hover" data-placement="right" data-content="Check-In is from 11:00"> <i class="fa fa-info-circl
`data-content` dùng `__()`

2017-09-12 02:55 UTC, ghost commented on resources/views/frontend/hotels/index.blade.php
> +                    <div class="popover-icon" data-container="body" data-toggle="popover" data-trigger="hover" data-placement="right" data-content="Check-out is from 12:00"> <i class="fa fa-info-circ
`data-content` dùng `__()`

2017-09-12 02:55 UTC, ghost commented on resources/views/frontend/hotels/index.blade.php
> +                    <div class="popover-icon" data-container="body" data-toggle="popover" data-trigger="hover" data-placement="right" data-content="Check-In is from 11:00"> <i class="fa fa-info-circl
Check lại `data-content`

2017-09-12 02:55 UTC, ghost commented on resources/views/frontend/hotels/index.blade.php
> +              <div class="room-thumb"> <img src="{{ isset($hotel->images[0])? asset($hotel->images[0]->path): asset(config('image.no_image')) }}" alt="hotel" class="img-presentive" />
1 dấu cách trước dấu `?` và `:`

2017-09-12 02:55 UTC, at-nhuibo commented on resources/views/frontend/layouts/partials/header.blade.php
> +          <li class="dropdown {{ isActiveRoute('frontend.index') }}"> <a href="/">Home</a>
Chữ Home dùng trong `__()` nha.

2017-09-12 02:55 UTC, at-nhuibo commented on resources/views/frontend/layouts/partials/header.blade.php
> +          <li class="{{ areActiveRoute(['frontend.hotel.index', 'frontend.hotel.show']) }}"> <a href="{{ route('frontend.hotel.index') }}">Hotels</b></a>
Chữ Hotels dùng `__()`

2017-09-12 02:55 UTC, at-nhuibo commented on resources/views/frontend/layouts/partials/header.blade.php
>            <li class="dropdown"> <a href="#" data-toggle="dropdown" class="dropdown-toggle js-activated">News<b class="caret"></b></a>
Chữ News dùng `__()`

2017-09-12 04:46 UTC, ghost reviewed
Hì, sorry e 1 cái nữa thôi!

2017-09-12 04:46 UTC, at-nhuibo commented on resources/views/frontend/hotels/index.blade.php
> +                    <label for="checkin">{{ __('Arangement') }}</label>
Chữ `Arangement` thiếu 1 chữ r: `Arrangement`. Mà dùng chữ `Order by` đi

2017-09-12 04:46 UTC, at-nhuibo commented on resources/views/frontend/hotels/index.blade.php
> +                    <div class="popover-icon" data-toggle="tooltip" title="{{ __('Default not arange') }}" data-placement="right"> <i class="fa fa-info-circle fa-lg"> </i> </div>
Default not arange => `Default is none`

2017-09-12 05:00 UTC, ghost approved these changes
LGTM. Thanks.

2017-09-12 06:48 UTC, at-minhnguyen commented
LGTM

2017-09-12 06:48 UTC, merged