Coding show place for user
AT-PHPIntership/hotel-booking pull request #360
Opened 2017-09-15 04:03 UTC by at-namnguyen

- Show place for user

2017-09-15 04:20 UTC, at-namnguyen commented
A @at-minhnguyen  assign cho mấy a trainner rv giúp em
<3

2017-09-15 09:51 UTC, ghost requested changes
Check my comment please...

2017-09-15 09:51 UTC, at-nhuibo commented on app/Http/Controllers/Frontend/PlaceController.php
> +        $with['hotelServices.service'] = function ($query) {
Để lấy service ra trực tiếp từ hotel thì dùng kiểu quan hệ ni nha: `belongsToMany`.

2017-09-15 09:51 UTC, at-nhuibo commented on resources/views/frontend/places/show.blade.php
> +            <h2><i class="fa fa-arrow-right" aria-hidden="true"></i>{{ __('Has :totalHolels hotels in here', ['totalHolels' => $place->hotels_count]) }}</h2>
Change text nha: `There are :total hotels in :place.`

2017-09-15 09:51 UTC, at-nhuibo commented on app/Model/HotelService.php
> +    const SHOW_LIMIT = 6;
Comment vào nó là cái gì nha!

2017-09-17 06:04 UTC, at-namnguyen commented
rv lại giúp e nha

2017-09-19 03:54 UTC, at-nhuibo commented on routes/web.php
> +    Route::get('place/{slug}', 'PlaceController@show')->name('place.show');
Đổi `place` thành `places` số nhiều nha. Url chuẩn là nên đặt số nhiều

2017-09-21 01:20 UTC, ghost approved these changes
LGTM. Thanks.

2017-09-21 01:36 UTC, at-minhnguyen commented
LGTM

2017-09-21 02:28 UTC, merged