Coding user booking
AT-PHPIntership/hotel-booking pull request #375
Opened 2017-09-20 17:41 UTC by at-namnguyen

- User booking room for User and Guest

2017-09-22 01:19 UTC, ghost requested changes
Check comments của mình nha! Thanks.

2017-09-22 01:19 UTC, at-nhuibo commented on app/Http/Controllers/Frontend/HotelController.php
> +        if (\Cache::has(User::KEY_CACHE)) {
Use Cache trước khi khai báo class, để hắn load class nớ trước, rồi chỉ dùng lại thôi, không cần dấu \ nữa.

2017-09-22 01:19 UTC, at-nhuibo commented on resources/views/frontend/booking/index.blade.php
> +              <input type="hidden" name="target" value="{{ (Auth::user()) ? 'user' : 'guest' }}">
Cái `user` và `guest` lấy từ model nha!!!

2017-09-22 04:28 UTC, ghost approved these changes
LGTM. Thanks.

2017-09-22 04:44 UTC, at-minhnguyen commented on app/Http/Controllers/Frontend/ReservationController.php
> +        if (isset($bookingInfomation)) {
Cái này phải check empty chứ nhỉ

2017-09-22 04:44 UTC, at-minhnguyen commented on app/Http/Controllers/Frontend/ReservationController.php
> +        $reservation = new Reservation($request->all());
Những đoạn code này ae nên dùng try{} catch() {} nhé

2017-09-26 02:18 UTC, at-minhnguyen commented on app/Http/Controllers/Frontend/ReservationController.php
> +        try {
Chỗ try {} catch () {} này đặt cả hàm chứ đặt cái create instence để làm chi đâu.
Update lại giúp anh nhé

2017-09-26 02:18 UTC, at-minhnguyen commented on public/frontend/js/reservation.js
> +        console.log(request);
Remove console.log

2017-09-26 02:18 UTC, at-minhnguyen commented on resources/views/frontend/booking/index.blade.php
> +@section('customcss')
Trường hợp những view mà nhiều block, nhiều source, nên tách ra các block thành các file, rồi include vào, dễ quản lý và handle nếu có issue

2017-09-26 02:57 UTC, at-namnguyen commented on resources/views/frontend/booking/index.blade.php
> +@section('customcss')
da, ok a

2017-09-26 04:09 UTC, at-minhnguyen commented
LGTM

2017-09-26 04:09 UTC, merged

2017-09-26 04:09 UTC, at-minhnguyen commented
Thank for your description :)